server:
  port: 8081
  name: tenet-server

log:
  level: debug

database:
  mysql: 
    host: localhost
    port: 3306
    username: root
    password: root
    database: oolong
  redis:
    host: localhost
    port: 6379
    db: 0