server:
  port: 8081
  name: tenet-server

log:
  level: debug

ai:
  deepseek:
    api_key: "sk-4af5b235f27546d9aedf30e3a7f390b0"

database:
  mysql: 
    host: localhost
    port: 3306
    username: root
    password: root
    database: oolong
  redis:
    host: localhost
    port: 6379
    db: 0